services:
    backend:
        build:
          context: ./simpleapi
          dockerfile: Dockerfile
        networks:
          - app-network
        env_file: 
          - .env 
        environment:
          POSTGRES_HOST: database
        depends_on:
          - database


    database:
        image: 
          postgres:17.2-alpine
        networks:
          - app-network
        env_file: 
          - .env 
        volumes:
          - pgdata:/var/lib/postgresql/data
          - ./initdb:/docker-entrypoint-initdb.d:ro


    httpd:
        build:
          context: ./http-server
          dockerfile: Dockerfile
        ports:
          - "8084:80"
        networks:
          - app-network
        depends_on:
          - backend

    adminer:
      image: adminer:latest
      container_name: adminer
      depends_on:
        - database
      networks:
        - app-network
      ports:
        - "8081:8080"


networks:
  app-network:

volumes:
  pgdata:
