services:
    backend:
        build:
          context: ./simpleapi
        networks:
          - app-network
        env_file: 
          - .env 
        environment:
          POSTGRES_HOST: database
        depends_on:
          - database


    database:
        build:
          context: ./initdb
        networks:
          - app-network
        env_file: 
          - .env 
        volumes:
          - pgdata:/var/lib/postgresql/data


    httpd:
        build:
          context: ./httpd-server
        ports:
          - "8084:80"
        networks:
          - app-network
        depends_on:
          - backend

    adminer:
      image: adminer:latest
      container_name: adminer
      depends_on:
        - database
      networks:
        - app-network
      ports:
        - "8081:8080"


networks:
  app-network:

volumes:
  pgdata:
