name: CI devops 2025
on:
  #to begin you want to launch this job in main and develop
  push:
    branches: [main, develop]  #se déclanche sur les branches main et develop
  pull_request: # et aussi sur les pull request

jobs:
  test-backend: 
    runs-on: ubuntu-24.04
    steps:
     #checkout your github code using actions/checkout@v4
      - uses: actions/checkout@v5

     #do the same with another action (actions/setup-java@v4) that enable to setup jdk 21
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'

     #finally build your app with the latest command
      - name: Build and test with Maven
        run: mvn clean verify --file ./simpleapi/pom.xml
